// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/blog/blog.proto

package blog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for BlogService service

type BlogService interface {
	FetchArticles(ctx context.Context, in *ListArticleRequest, opts ...client.CallOption) (*ArticleResult, error)
	CreateArticle(ctx context.Context, in *Article, opts ...client.CallOption) (*ArticleResult, error)
	DeleteArticle(ctx context.Context, in *Article, opts ...client.CallOption) (*ArticleResult, error)
	UpdateArticle(ctx context.Context, in *Article, opts ...client.CallOption) (*ArticleResult, error)
}

type blogService struct {
	c    client.Client
	name string
}

func NewBlogService(name string, c client.Client) BlogService {
	return &blogService{
		c:    c,
		name: name,
	}
}

func (c *blogService) FetchArticles(ctx context.Context, in *ListArticleRequest, opts ...client.CallOption) (*ArticleResult, error) {
	req := c.c.NewRequest(c.name, "BlogService.FetchArticles", in)
	out := new(ArticleResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogService) CreateArticle(ctx context.Context, in *Article, opts ...client.CallOption) (*ArticleResult, error) {
	req := c.c.NewRequest(c.name, "BlogService.CreateArticle", in)
	out := new(ArticleResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogService) DeleteArticle(ctx context.Context, in *Article, opts ...client.CallOption) (*ArticleResult, error) {
	req := c.c.NewRequest(c.name, "BlogService.DeleteArticle", in)
	out := new(ArticleResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogService) UpdateArticle(ctx context.Context, in *Article, opts ...client.CallOption) (*ArticleResult, error) {
	req := c.c.NewRequest(c.name, "BlogService.UpdateArticle", in)
	out := new(ArticleResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BlogService service

type BlogServiceHandler interface {
	FetchArticles(context.Context, *ListArticleRequest, *ArticleResult) error
	CreateArticle(context.Context, *Article, *ArticleResult) error
	DeleteArticle(context.Context, *Article, *ArticleResult) error
	UpdateArticle(context.Context, *Article, *ArticleResult) error
}

func RegisterBlogServiceHandler(s server.Server, hdlr BlogServiceHandler, opts ...server.HandlerOption) error {
	type blogService interface {
		FetchArticles(ctx context.Context, in *ListArticleRequest, out *ArticleResult) error
		CreateArticle(ctx context.Context, in *Article, out *ArticleResult) error
		DeleteArticle(ctx context.Context, in *Article, out *ArticleResult) error
		UpdateArticle(ctx context.Context, in *Article, out *ArticleResult) error
	}
	type BlogService struct {
		blogService
	}
	h := &blogServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&BlogService{h}, opts...))
}

type blogServiceHandler struct {
	BlogServiceHandler
}

func (h *blogServiceHandler) FetchArticles(ctx context.Context, in *ListArticleRequest, out *ArticleResult) error {
	return h.BlogServiceHandler.FetchArticles(ctx, in, out)
}

func (h *blogServiceHandler) CreateArticle(ctx context.Context, in *Article, out *ArticleResult) error {
	return h.BlogServiceHandler.CreateArticle(ctx, in, out)
}

func (h *blogServiceHandler) DeleteArticle(ctx context.Context, in *Article, out *ArticleResult) error {
	return h.BlogServiceHandler.DeleteArticle(ctx, in, out)
}

func (h *blogServiceHandler) UpdateArticle(ctx context.Context, in *Article, out *ArticleResult) error {
	return h.BlogServiceHandler.UpdateArticle(ctx, in, out)
}
