// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/blog/blog.proto

package blog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListArticleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListArticleRequest) Reset()         { *m = ListArticleRequest{} }
func (m *ListArticleRequest) String() string { return proto.CompactTextString(m) }
func (*ListArticleRequest) ProtoMessage()    {}
func (*ListArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e11f767506fb4e, []int{0}
}

func (m *ListArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListArticleRequest.Unmarshal(m, b)
}
func (m *ListArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListArticleRequest.Marshal(b, m, deterministic)
}
func (m *ListArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListArticleRequest.Merge(m, src)
}
func (m *ListArticleRequest) XXX_Size() int {
	return xxx_messageInfo_ListArticleRequest.Size(m)
}
func (m *ListArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListArticleRequest proto.InternalMessageInfo

type Article struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Author               *Author  `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e11f767506fb4e, []int{1}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Article) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Article) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Article) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type Author struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e11f767506fb4e, []int{2}
}

func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (m *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(m, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ArticleResult struct {
	StatusCode           int32      `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Article              *Article   `protobuf:"bytes,3,opt,name=article,proto3" json:"article,omitempty"`
	Articles             []*Article `protobuf:"bytes,4,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ArticleResult) Reset()         { *m = ArticleResult{} }
func (m *ArticleResult) String() string { return proto.CompactTextString(m) }
func (*ArticleResult) ProtoMessage()    {}
func (*ArticleResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e11f767506fb4e, []int{3}
}

func (m *ArticleResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleResult.Unmarshal(m, b)
}
func (m *ArticleResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleResult.Marshal(b, m, deterministic)
}
func (m *ArticleResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleResult.Merge(m, src)
}
func (m *ArticleResult) XXX_Size() int {
	return xxx_messageInfo_ArticleResult.Size(m)
}
func (m *ArticleResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleResult.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleResult proto.InternalMessageInfo

func (m *ArticleResult) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ArticleResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ArticleResult) GetArticle() *Article {
	if m != nil {
		return m.Article
	}
	return nil
}

func (m *ArticleResult) GetArticles() []*Article {
	if m != nil {
		return m.Articles
	}
	return nil
}

type ListCategoryRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCategoryRequest) Reset()         { *m = ListCategoryRequest{} }
func (m *ListCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*ListCategoryRequest) ProtoMessage()    {}
func (*ListCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e11f767506fb4e, []int{4}
}

func (m *ListCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoryRequest.Unmarshal(m, b)
}
func (m *ListCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoryRequest.Marshal(b, m, deterministic)
}
func (m *ListCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoryRequest.Merge(m, src)
}
func (m *ListCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_ListCategoryRequest.Size(m)
}
func (m *ListCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoryRequest proto.InternalMessageInfo

type Category struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color                string   `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e11f767506fb4e, []int{5}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Category) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Category) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type CategoryResult struct {
	StatusCode           int32       `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Categories           []*Category `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CategoryResult) Reset()         { *m = CategoryResult{} }
func (m *CategoryResult) String() string { return proto.CompactTextString(m) }
func (*CategoryResult) ProtoMessage()    {}
func (*CategoryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6e11f767506fb4e, []int{6}
}

func (m *CategoryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryResult.Unmarshal(m, b)
}
func (m *CategoryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryResult.Marshal(b, m, deterministic)
}
func (m *CategoryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryResult.Merge(m, src)
}
func (m *CategoryResult) XXX_Size() int {
	return xxx_messageInfo_CategoryResult.Size(m)
}
func (m *CategoryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryResult.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryResult proto.InternalMessageInfo

func (m *CategoryResult) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *CategoryResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CategoryResult) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

func init() {
	proto.RegisterType((*ListArticleRequest)(nil), "ListArticleRequest")
	proto.RegisterType((*Article)(nil), "Article")
	proto.RegisterType((*Author)(nil), "Author")
	proto.RegisterType((*ArticleResult)(nil), "ArticleResult")
	proto.RegisterType((*ListCategoryRequest)(nil), "ListCategoryRequest")
	proto.RegisterType((*Category)(nil), "Category")
	proto.RegisterType((*CategoryResult)(nil), "CategoryResult")
}

func init() {
	proto.RegisterFile("proto/blog/blog.proto", fileDescriptor_e6e11f767506fb4e)
}

var fileDescriptor_e6e11f767506fb4e = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xc1, 0xea, 0xd3, 0x40,
	0x10, 0xc6, 0xd9, 0xa6, 0x4d, 0xda, 0x09, 0xed, 0x61, 0xff, 0x2d, 0x2c, 0x82, 0x18, 0x82, 0x87,
	0xf6, 0x12, 0xa1, 0xfa, 0x02, 0xb1, 0xe2, 0xc9, 0x53, 0xc4, 0x73, 0xd9, 0x6e, 0x86, 0x34, 0x90,
	0x76, 0x6b, 0x76, 0x52, 0xf0, 0xea, 0x33, 0xf8, 0x10, 0x3e, 0x88, 0x0f, 0x26, 0xd9, 0x64, 0xa3,
	0xb5, 0x82, 0x42, 0x2f, 0x65, 0xbf, 0xef, 0x9b, 0x0e, 0x33, 0xbf, 0xdd, 0xc0, 0xea, 0x52, 0x6b,
	0xd2, 0xaf, 0x0e, 0x95, 0x2e, 0xec, 0x4f, 0x62, 0x75, 0xbc, 0x04, 0xfe, 0xa1, 0x34, 0x94, 0xd6,
	0x54, 0xaa, 0x0a, 0x33, 0xfc, 0xdc, 0xa0, 0xa1, 0xf8, 0x3b, 0x83, 0xa0, 0xb7, 0xf8, 0x02, 0x46,
	0x65, 0x2e, 0x58, 0xc4, 0xd6, 0x5e, 0x36, 0x2a, 0x73, 0xbe, 0x84, 0x09, 0x95, 0x54, 0xa1, 0x18,
	0x45, 0x6c, 0x3d, 0xcb, 0x3a, 0xc1, 0x05, 0x04, 0x4a, 0x9f, 0x09, 0xcf, 0x24, 0x3c, 0xeb, 0x3b,
	0xc9, 0x5f, 0x80, 0x2f, 0x1b, 0x3a, 0xea, 0x5a, 0x8c, 0x23, 0xb6, 0x0e, 0xb7, 0x41, 0x92, 0x5a,
	0x99, 0xf5, 0x36, 0x7f, 0x0e, 0xa0, 0x6a, 0x94, 0x84, 0xf9, 0x5e, 0x92, 0x98, 0xd8, 0x7f, 0xcf,
	0x7a, 0x27, 0xa5, 0x36, 0x6e, 0x2e, 0xb9, 0x8b, 0xfd, 0x2e, 0xee, 0x9d, 0x94, 0x62, 0x01, 0x7e,
	0xd7, 0xef, 0xcf, 0x41, 0xe3, 0x6f, 0x0c, 0xe6, 0xc3, 0x5e, 0xa6, 0xa9, 0xda, 0x51, 0x42, 0x43,
	0x92, 0x1a, 0xb3, 0x57, 0x3a, 0x47, 0x5b, 0x3a, 0xc9, 0xa0, 0xb3, 0x76, 0x3a, 0xb7, 0x5b, 0x9c,
	0xd0, 0x18, 0x59, 0xb8, 0xed, 0x9c, 0xe4, 0x31, 0x04, 0xb2, 0xeb, 0x65, 0xf7, 0x0b, 0xb7, 0xd3,
	0xc4, 0xf5, 0x76, 0x01, 0x7f, 0x09, 0xd3, 0xfe, 0x68, 0xc4, 0x38, 0xf2, 0x6e, 0x8a, 0x86, 0x24,
	0x5e, 0xc1, 0x53, 0x4b, 0x7c, 0x27, 0x09, 0x0b, 0x5d, 0x7f, 0x71, 0xc8, 0xbf, 0x32, 0x98, 0x3a,
	0xef, 0x8e, 0x39, 0x87, 0xf1, 0x59, 0x9e, 0xdc, 0x50, 0xf6, 0xdc, 0xde, 0x83, 0xd2, 0x95, 0xae,
	0x7b, 0xde, 0x9d, 0x78, 0x10, 0xe6, 0x15, 0x16, 0xbf, 0xe6, 0x7a, 0x14, 0xd9, 0x06, 0x40, 0x75,
	0xcd, 0x4a, 0x34, 0xc2, 0xb3, 0x40, 0x66, 0xc9, 0xd0, 0xff, 0xb7, 0x70, 0xfb, 0x83, 0x41, 0xf8,
	0xb6, 0xd2, 0xc5, 0x47, 0xac, 0xaf, 0xa5, 0x42, 0xfe, 0x06, 0xe6, 0xef, 0x91, 0xd4, 0xb1, 0xa7,
	0x67, 0xf8, 0x53, 0x72, 0xff, 0x4a, 0x9f, 0x2d, 0x92, 0xdb, 0xeb, 0xdd, 0xc0, 0x7c, 0x67, 0x37,
	0x75, 0x4f, 0x77, 0xc0, 0xff, 0xb7, 0xd2, 0x77, 0x58, 0xe1, 0x7f, 0x96, 0x7e, 0xb2, 0x80, 0xfe,
	0x59, 0x7a, 0xf0, 0xed, 0x37, 0xf5, 0xfa, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x1b, 0xb9,
	0xda, 0x6c, 0x03, 0x00, 0x00,
}
