// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/blog.proto

package blog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListArticleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListArticleRequest) Reset()         { *m = ListArticleRequest{} }
func (m *ListArticleRequest) String() string { return proto.CompactTextString(m) }
func (*ListArticleRequest) ProtoMessage()    {}
func (*ListArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{0}
}

func (m *ListArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListArticleRequest.Unmarshal(m, b)
}
func (m *ListArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListArticleRequest.Marshal(b, m, deterministic)
}
func (m *ListArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListArticleRequest.Merge(m, src)
}
func (m *ListArticleRequest) XXX_Size() int {
	return xxx_messageInfo_ListArticleRequest.Size(m)
}
func (m *ListArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListArticleRequest proto.InternalMessageInfo

type Article struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId             int64    `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{1}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Article) GetAuthorId() int64 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

func (m *Article) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Article) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type ArticleResult struct {
	StatusCode           int32      `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Article              *Article   `protobuf:"bytes,3,opt,name=article,proto3" json:"article,omitempty"`
	Articles             []*Article `protobuf:"bytes,4,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ArticleResult) Reset()         { *m = ArticleResult{} }
func (m *ArticleResult) String() string { return proto.CompactTextString(m) }
func (*ArticleResult) ProtoMessage()    {}
func (*ArticleResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{2}
}

func (m *ArticleResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleResult.Unmarshal(m, b)
}
func (m *ArticleResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleResult.Marshal(b, m, deterministic)
}
func (m *ArticleResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleResult.Merge(m, src)
}
func (m *ArticleResult) XXX_Size() int {
	return xxx_messageInfo_ArticleResult.Size(m)
}
func (m *ArticleResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleResult.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleResult proto.InternalMessageInfo

func (m *ArticleResult) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ArticleResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ArticleResult) GetArticle() *Article {
	if m != nil {
		return m.Article
	}
	return nil
}

func (m *ArticleResult) GetArticles() []*Article {
	if m != nil {
		return m.Articles
	}
	return nil
}

type ListCategoryRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCategoryRequest) Reset()         { *m = ListCategoryRequest{} }
func (m *ListCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*ListCategoryRequest) ProtoMessage()    {}
func (*ListCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{3}
}

func (m *ListCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoryRequest.Unmarshal(m, b)
}
func (m *ListCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoryRequest.Marshal(b, m, deterministic)
}
func (m *ListCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoryRequest.Merge(m, src)
}
func (m *ListCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_ListCategoryRequest.Size(m)
}
func (m *ListCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoryRequest proto.InternalMessageInfo

type Category struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color                string   `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{4}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Category) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Category) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type CategoryResult struct {
	StatusCode           int32       `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Categories           []*Category `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CategoryResult) Reset()         { *m = CategoryResult{} }
func (m *CategoryResult) String() string { return proto.CompactTextString(m) }
func (*CategoryResult) ProtoMessage()    {}
func (*CategoryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{5}
}

func (m *CategoryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryResult.Unmarshal(m, b)
}
func (m *CategoryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryResult.Marshal(b, m, deterministic)
}
func (m *CategoryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryResult.Merge(m, src)
}
func (m *CategoryResult) XXX_Size() int {
	return xxx_messageInfo_CategoryResult.Size(m)
}
func (m *CategoryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryResult.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryResult proto.InternalMessageInfo

func (m *CategoryResult) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *CategoryResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CategoryResult) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

func init() {
	proto.RegisterType((*ListArticleRequest)(nil), "ListArticleRequest")
	proto.RegisterType((*Article)(nil), "Article")
	proto.RegisterType((*ArticleResult)(nil), "ArticleResult")
	proto.RegisterType((*ListCategoryRequest)(nil), "ListCategoryRequest")
	proto.RegisterType((*Category)(nil), "Category")
	proto.RegisterType((*CategoryResult)(nil), "CategoryResult")
}

func init() {
	proto.RegisterFile("proto/blog.proto", fileDescriptor_fc5203cdc85000bc)
}

var fileDescriptor_fc5203cdc85000bc = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0x49, 0xb2, 0xdb, 0x4d, 0xde, 0xb2, 0xa9, 0x4c, 0x57, 0x18, 0x2a, 0xe2, 0x12, 0x3c,
	0xb4, 0x20, 0x11, 0xaa, 0x07, 0xaf, 0x6b, 0x44, 0x10, 0x3c, 0x45, 0x3c, 0x2f, 0xd3, 0x99, 0x47,
	0x3a, 0x90, 0xee, 0xd4, 0xcc, 0x4b, 0xc1, 0xab, 0x9f, 0xc1, 0x8f, 0xe0, 0xd1, 0x0f, 0x29, 0x3b,
	0x93, 0x49, 0xad, 0x5b, 0xb0, 0xb0, 0xb7, 0x79, 0xff, 0xff, 0xcb, 0xe3, 0x3f, 0xbf, 0x79, 0x81,
	0x27, 0x37, 0x9d, 0x21, 0xf3, 0xfa, 0xb2, 0x35, 0x4d, 0xe9, 0x8e, 0xc5, 0x12, 0xd8, 0x67, 0x6d,
	0x69, 0xdd, 0x91, 0x96, 0x2d, 0xd6, 0xf8, 0xad, 0x47, 0x4b, 0xc5, 0xaf, 0x08, 0x66, 0x83, 0xc4,
	0x72, 0x88, 0xb5, 0xe2, 0xd1, 0x2a, 0x3a, 0x4b, 0xea, 0x58, 0x2b, 0xb6, 0x84, 0x29, 0x69, 0x6a,
	0x91, 0xc7, 0xab, 0xe8, 0x2c, 0xab, 0x7d, 0xc1, 0x38, 0xcc, 0xa4, 0xd9, 0x12, 0x6e, 0x89, 0x27,
	0x4e, 0x0f, 0x25, 0x7b, 0x06, 0x99, 0xe8, 0xe9, 0xca, 0x74, 0x1b, 0xad, 0xf8, 0xc4, 0x8d, 0x49,
	0xbd, 0xf0, 0x49, 0xb1, 0xe7, 0x00, 0xb2, 0x43, 0x41, 0xa8, 0x36, 0x82, 0xf8, 0xd4, 0x7d, 0x99,
	0x0d, 0xca, 0x9a, 0x76, 0x76, 0x7f, 0xa3, 0x82, 0x7d, 0xe4, 0xed, 0x41, 0x59, 0x53, 0xf1, 0x33,
	0x82, 0xc5, 0x98, 0xdc, 0xf6, 0x2d, 0xb1, 0x17, 0x30, 0xb7, 0x24, 0xa8, 0xb7, 0x1b, 0x69, 0x14,
	0xba, 0xd4, 0xd3, 0x1a, 0xbc, 0x54, 0x19, 0xe5, 0x72, 0x5e, 0xa3, 0xb5, 0xa2, 0x09, 0xf9, 0x43,
	0xc9, 0x0a, 0x98, 0x09, 0x3f, 0xcb, 0xdd, 0x60, 0x7e, 0x91, 0x96, 0x61, 0x76, 0x30, 0xd8, 0x4b,
	0x48, 0x87, 0xa3, 0xe5, 0x93, 0x55, 0x72, 0xaf, 0x69, 0x74, 0x8a, 0xa7, 0x70, 0xb2, 0x63, 0x5a,
	0x09, 0xc2, 0xc6, 0x74, 0xdf, 0x03, 0xd4, 0x1f, 0x11, 0xa4, 0x41, 0xdb, 0xa3, 0xca, 0x60, 0xb2,
	0x15, 0xd7, 0x21, 0x94, 0x3b, 0xef, 0x48, 0x4b, 0xd3, 0x9a, 0x6e, 0x20, 0xea, 0x8b, 0x03, 0x91,
	0xdd, 0x42, 0x7e, 0x97, 0xeb, 0x50, 0x64, 0xe7, 0x00, 0xd2, 0x0f, 0xd3, 0x68, 0x79, 0xe2, 0x80,
	0x64, 0xe5, 0x38, 0xff, 0x2f, 0xf3, 0xe2, 0x77, 0x0c, 0xf3, 0xf7, 0xad, 0x69, 0xbe, 0x60, 0x77,
	0xab, 0x25, 0xb2, 0xb7, 0xb0, 0xf8, 0x88, 0x24, 0xaf, 0x06, 0x7a, 0x96, 0x9d, 0x94, 0xfb, 0x7b,
	0x78, 0x9a, 0x97, 0xf7, 0x9f, 0xf7, 0x1c, 0x16, 0x95, 0xbb, 0x69, 0x58, 0xce, 0x11, 0xff, 0x43,
	0xad, 0x1f, 0xb0, 0xc5, 0x47, 0xb6, 0x7e, 0x75, 0x80, 0xfe, 0xdf, 0xfa, 0x0e, 0x8e, 0x5d, 0xec,
	0x6a, 0xbc, 0x19, 0x5b, 0x96, 0x0f, 0x3c, 0xf6, 0xe9, 0x71, 0xf9, 0x0f, 0xe6, 0x57, 0x90, 0xfb,
	0xe8, 0xe3, 0x0a, 0xdc, 0x91, 0xda, 0xeb, 0xbe, 0x3c, 0x72, 0x7f, 0xe7, 0x9b, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xc4, 0x33, 0x68, 0x88, 0xb1, 0x03, 0x00, 0x00,
}
