// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/blogs.proto

package blogs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_DRAFTED   Status = 0
	Status_PUBLISHED Status = 1
)

var Status_name = map[int32]string{
	0: "DRAFTED",
	1: "PUBLISHED",
}

var Status_value = map[string]int32{
	"DRAFTED":   0,
	"PUBLISHED": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_46dad7d5fa437d3a, []int{0}
}

type Article struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug                 string   `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Author               *Author  `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Topic                *Topic   `protobuf:"bytes,6,opt,name=topic,proto3" json:"topic,omitempty"`
	IsPublished          bool     `protobuf:"varint,7,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	PublishedAt          int64    `protobuf:"varint,8,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	CreatedAt            int64    `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            int64    `protobuf:"varint,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_46dad7d5fa437d3a, []int{0}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Article) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Article) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Article) GetTopic() *Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *Article) GetIsPublished() bool {
	if m != nil {
		return m.IsPublished
	}
	return false
}

func (m *Article) GetPublishedAt() int64 {
	if m != nil {
		return m.PublishedAt
	}
	return 0
}

func (m *Article) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Article) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Article) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

type Topic struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Slug                 string   `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Color                string   `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            int64    `protobuf:"varint,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_46dad7d5fa437d3a, []int{1}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Topic) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Topic) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Topic) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Topic) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Topic) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Topic) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Topic) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

type Author struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DeletedAt            int64    `protobuf:"varint,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_46dad7d5fa437d3a, []int{2}
}

func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (m *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(m, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Author) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Author) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

type ListRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Status               Status   `protobuf:"varint,3,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46dad7d5fa437d3a, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRequest) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_DRAFTED
}

type ListResponse struct {
	Articles             []*Article `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	Topics               []*Topic   `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_46dad7d5fa437d3a, []int{4}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetArticles() []*Article {
	if m != nil {
		return m.Articles
	}
	return nil
}

func (m *ListResponse) GetTopics() []*Topic {
	if m != nil {
		return m.Topics
	}
	return nil
}

type Response struct {
	Article              *Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	Topic                *Topic   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_46dad7d5fa437d3a, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetArticle() *Article {
	if m != nil {
		return m.Article
	}
	return nil
}

func (m *Response) GetTopic() *Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

func init() {
	proto.RegisterEnum("Status", Status_name, Status_value)
	proto.RegisterType((*Article)(nil), "Article")
	proto.RegisterType((*Topic)(nil), "Topic")
	proto.RegisterType((*Author)(nil), "Author")
	proto.RegisterType((*ListRequest)(nil), "ListRequest")
	proto.RegisterType((*ListResponse)(nil), "ListResponse")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() {
	proto.RegisterFile("proto/blogs.proto", fileDescriptor_46dad7d5fa437d3a)
}

var fileDescriptor_46dad7d5fa437d3a = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x4e, 0xfc, 0x35, 0x4e, 0xaa, 0xb0, 0xea, 0x61, 0x55, 0x51, 0x30, 0x51, 0x0f, 0x56,
	0x85, 0x8c, 0x14, 0x7e, 0x81, 0x4b, 0x5a, 0x40, 0xe4, 0x50, 0x6d, 0x53, 0x89, 0x5b, 0xe5, 0x38,
	0xab, 0x64, 0x25, 0x37, 0x36, 0xd9, 0xf5, 0x3f, 0xe1, 0xff, 0x70, 0xe3, 0x77, 0x21, 0xcf, 0xae,
	0x4d, 0x64, 0x20, 0xed, 0x6d, 0xe6, 0xbd, 0xc9, 0xd3, 0xbc, 0xf1, 0xdb, 0xc0, 0xcb, 0x6a, 0x5f,
	0xaa, 0xf2, 0xfd, 0xaa, 0x28, 0x37, 0x32, 0xc1, 0x7a, 0xfa, 0xd3, 0x06, 0x2f, 0xdd, 0x2b, 0x91,
	0x17, 0x9c, 0x9c, 0x80, 0x2d, 0xd6, 0xd4, 0x8a, 0xac, 0x78, 0xcc, 0x6c, 0xb1, 0x26, 0xa7, 0xe0,
	0x28, 0xa1, 0x0a, 0x4e, 0xed, 0xc8, 0x8a, 0x03, 0xa6, 0x1b, 0x42, 0x60, 0x28, 0x8b, 0x7a, 0x43,
	0x07, 0x08, 0x62, 0x4d, 0x28, 0x78, 0x79, 0xb9, 0x53, 0x7c, 0xa7, 0xe8, 0x10, 0xe1, 0xb6, 0x25,
	0x6f, 0xc0, 0xcd, 0x6a, 0xb5, 0x2d, 0xf7, 0xd4, 0x89, 0xac, 0x38, 0x9c, 0x79, 0x49, 0x8a, 0x2d,
	0x33, 0x30, 0x79, 0x05, 0x8e, 0x2a, 0x2b, 0x91, 0x53, 0x17, 0x79, 0x37, 0x59, 0x36, 0x1d, 0xd3,
	0x20, 0x79, 0x0b, 0x23, 0x21, 0x1f, 0xaa, 0x7a, 0x55, 0x08, 0xb9, 0xe5, 0x6b, 0xea, 0x45, 0x56,
	0xec, 0xb3, 0x50, 0xc8, 0xdb, 0x16, 0x6a, 0x46, 0x3a, 0xfe, 0x21, 0x53, 0xd4, 0x8f, 0xac, 0x78,
	0xc0, 0xc2, 0x0e, 0x4b, 0x15, 0x39, 0x07, 0xc8, 0xf7, 0x3c, 0x53, 0x7a, 0x20, 0xc0, 0x81, 0xc0,
	0x20, 0x9a, 0xae, 0xab, 0x75, 0x4b, 0x83, 0xa6, 0x0d, 0xa2, 0xe9, 0x35, 0x2f, 0xb8, 0xa1, 0x43,
	0x4d, 0x1b, 0x24, 0x55, 0xd3, 0x5f, 0x16, 0x38, 0xb8, 0xf3, 0x33, 0xef, 0x37, 0x81, 0x81, 0xca,
	0xda, 0xf3, 0x35, 0x65, 0x77, 0xd1, 0xe1, 0xc1, 0x45, 0x4f, 0xc1, 0xc9, 0xcb, 0xc2, 0x9c, 0x2d,
	0x60, 0xba, 0xe9, 0x19, 0x71, 0x8f, 0x1b, 0xf1, 0x8e, 0x1b, 0xf1, 0xfb, 0x46, 0xbe, 0x82, 0xab,
	0xbf, 0xcd, 0x5f, 0x46, 0x08, 0x0c, 0x77, 0xd9, 0x63, 0xeb, 0x03, 0xeb, 0x9e, 0xd8, 0xa0, 0x2f,
	0xf6, 0x0d, 0xc2, 0x85, 0x90, 0x8a, 0xf1, 0xef, 0x35, 0x97, 0xaa, 0x51, 0xa8, 0xb2, 0x0d, 0x47,
	0x4d, 0x87, 0x61, 0xdd, 0x58, 0x2c, 0xc4, 0xa3, 0x50, 0x28, 0xeb, 0x30, 0xdd, 0x34, 0x81, 0x91,
	0x2a, 0x53, 0xb5, 0x44, 0xcd, 0x93, 0x99, 0x97, 0xdc, 0x61, 0xcb, 0x0c, 0x3c, 0x5d, 0xc2, 0x48,
	0x2b, 0xcb, 0xaa, 0xdc, 0x49, 0x4e, 0x2e, 0xc0, 0xcf, 0x74, 0x80, 0x25, 0xb5, 0xa2, 0x41, 0x1c,
	0xce, 0xfc, 0xc4, 0x24, 0x9a, 0x75, 0x0c, 0x79, 0x0d, 0x2e, 0x26, 0x4a, 0x52, 0x1b, 0x67, 0xda,
	0x9c, 0x19, 0x74, 0xba, 0x00, 0xbf, 0x53, 0x9c, 0x82, 0x67, 0x7e, 0x87, 0xfb, 0x1e, 0x0a, 0xb6,
	0xc4, 0x9f, 0xd8, 0xda, 0xff, 0x88, 0xed, 0xe5, 0x05, 0xb8, 0x7a, 0x6b, 0x12, 0x82, 0x37, 0x67,
	0xe9, 0xcd, 0xf2, 0x7a, 0x3e, 0x79, 0x41, 0xc6, 0x10, 0xdc, 0xde, 0x5f, 0x2d, 0xbe, 0xdc, 0x7d,
	0xbe, 0x9e, 0x4f, 0xac, 0xd9, 0x0f, 0x1b, 0x9c, 0xab, 0xe6, 0x2d, 0x92, 0x77, 0x30, 0xbe, 0xe1,
	0x2a, 0xdf, 0xa6, 0xed, 0xba, 0xa3, 0xe4, 0xe0, 0x7a, 0x67, 0xe3, 0xa4, 0xe7, 0x78, 0xfc, 0x11,
	0xbf, 0x79, 0xfb, 0x70, 0xbb, 0xfd, 0xce, 0x82, 0xe4, 0x70, 0x6a, 0x8e, 0x9f, 0xe3, 0xa9, 0xa9,
	0x7b, 0x0c, 0xc8, 0xd1, 0xa9, 0x4b, 0x08, 0x71, 0x3f, 0x34, 0xf9, 0xc4, 0x76, 0x11, 0x84, 0x7a,
	0x3b, 0xfd, 0x28, 0xcc, 0x65, 0x0e, 0xd5, 0xce, 0xc1, 0xff, 0xc4, 0xd5, 0xff, 0xe8, 0x95, 0x8b,
	0xff, 0x4c, 0x1f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x1a, 0x4f, 0xab, 0xae, 0x04, 0x00,
	0x00,
}
