// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/blogs.proto

package blogs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46dad7d5fa437d3a, []int{0}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Article struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug                 string   `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId             uint32   `protobuf:"varint,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Topic                *Topic   `protobuf:"bytes,6,opt,name=topic,proto3" json:"topic,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            int64    `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_46dad7d5fa437d3a, []int{1}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Article) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Article) GetAuthorId() uint32 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

func (m *Article) GetTopic() *Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *Article) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Article) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Article) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Topic struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Slug                 string   `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Color                string   `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_46dad7d5fa437d3a, []int{2}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Topic) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Topic) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Topic) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Topic) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Topic) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Topic) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type ListResponse struct {
	Error                *Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Articles             []*Article `protobuf:"bytes,2,rep,name=articles,proto3" json:"articles,omitempty"`
	Topics               []*Topic   `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_46dad7d5fa437d3a, []int{3}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ListResponse) GetArticles() []*Article {
	if m != nil {
		return m.Articles
	}
	return nil
}

func (m *ListResponse) GetTopics() []*Topic {
	if m != nil {
		return m.Topics
	}
	return nil
}

type Response struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Article              *Article `protobuf:"bytes,2,opt,name=article,proto3" json:"article,omitempty"`
	Topic                *Topic   `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_46dad7d5fa437d3a, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetArticle() *Article {
	if m != nil {
		return m.Article
	}
	return nil
}

func (m *Response) GetTopic() *Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_46dad7d5fa437d3a, []int{5}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "ListRequest")
	proto.RegisterType((*Article)(nil), "Article")
	proto.RegisterType((*Topic)(nil), "Topic")
	proto.RegisterType((*ListResponse)(nil), "ListResponse")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Error)(nil), "Error")
}

func init() {
	proto.RegisterFile("proto/blogs.proto", fileDescriptor_46dad7d5fa437d3a)
}

var fileDescriptor_46dad7d5fa437d3a = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6b, 0xdc, 0x30,
	0x10, 0xc5, 0xeb, 0x95, 0xd7, 0x1e, 0x27, 0xa5, 0x15, 0xa1, 0x88, 0xb4, 0x29, 0xc6, 0xe4, 0xb0,
	0xf4, 0xe0, 0xc2, 0x96, 0xd2, 0xf3, 0xf6, 0x0b, 0x0a, 0x3d, 0x89, 0xf6, 0x1c, 0x1c, 0x5b, 0x6c,
	0x54, 0x9c, 0x95, 0x2b, 0x8d, 0x7f, 0x53, 0xff, 0x52, 0x7f, 0x45, 0x7f, 0x43, 0xd1, 0xc8, 0xde,
	0x3a, 0x21, 0x2c, 0xb9, 0xcd, 0x7b, 0xcf, 0x1a, 0x3d, 0xbd, 0x19, 0xc3, 0xb3, 0xde, 0x1a, 0x34,
	0x6f, 0xae, 0x3b, 0xb3, 0x73, 0x15, 0xd5, 0xe5, 0x7b, 0xc8, 0xbf, 0x69, 0x87, 0x52, 0xfd, 0x1a,
	0x94, 0x43, 0xce, 0x61, 0xd9, 0xd7, 0x3b, 0x25, 0xa2, 0x22, 0x5a, 0x33, 0x49, 0x35, 0x3f, 0x03,
	0xd6, 0xe9, 0x5b, 0x8d, 0x62, 0x41, 0x64, 0x00, 0xe5, 0xdf, 0x08, 0x56, 0x5b, 0x8b, 0xba, 0xe9,
	0x14, 0x7f, 0x02, 0x0b, 0xdd, 0xd2, 0x99, 0x53, 0xb9, 0xd0, 0xad, 0x3f, 0x81, 0x1a, 0x3b, 0x45,
	0x27, 0x32, 0x19, 0x80, 0xef, 0xed, 0xba, 0x61, 0x27, 0x62, 0x22, 0xa9, 0xe6, 0x02, 0x56, 0x8d,
	0xd9, 0xa3, 0xda, 0xa3, 0x58, 0x12, 0x3d, 0x41, 0xfe, 0x02, 0xb2, 0x7a, 0xc0, 0x1b, 0x63, 0xaf,
	0x74, 0x2b, 0x18, 0xb5, 0x4e, 0x03, 0xf1, 0xb5, 0xe5, 0x2f, 0x81, 0xa1, 0xe9, 0x75, 0x23, 0x92,
	0x22, 0x5a, 0xe7, 0x9b, 0xa4, 0xfa, 0xee, 0x91, 0x0c, 0x24, 0x7f, 0x0e, 0x89, 0xc3, 0x1a, 0x07,
	0x27, 0x56, 0xd4, 0x73, 0x44, 0xfc, 0x02, 0xa0, 0xb1, 0xaa, 0x46, 0xd5, 0x5e, 0xd5, 0x28, 0xd2,
	0x22, 0x5a, 0xc7, 0x32, 0x1b, 0x99, 0x2d, 0x7a, 0x79, 0xe8, 0xdb, 0x49, 0xce, 0x82, 0x3c, 0x32,
	0x5b, 0x2c, 0x7f, 0x47, 0xc0, 0xe8, 0x9a, 0x47, 0x3e, 0xf7, 0x29, 0xc4, 0x58, 0x4f, 0xaf, 0xf5,
	0xe5, 0x21, 0x80, 0xe5, 0x2c, 0x80, 0x33, 0x60, 0x8d, 0xe9, 0x8c, 0xa5, 0x27, 0x66, 0x32, 0x80,
	0x7b, 0x4e, 0x93, 0xe3, 0x4e, 0x57, 0xf7, 0x9d, 0x5a, 0x38, 0x09, 0x33, 0x75, 0xbd, 0xd9, 0x3b,
	0xe5, 0xd3, 0x52, 0xd6, 0x1a, 0x4b, 0x96, 0x7d, 0x5a, 0x9f, 0x3d, 0x92, 0x81, 0xe4, 0x97, 0x90,
	0xd6, 0x61, 0x8e, 0x4e, 0x2c, 0x8a, 0x78, 0x9d, 0x6f, 0xd2, 0x6a, 0x1c, 0xac, 0x3c, 0x28, 0xfc,
	0x15, 0x24, 0x14, 0xae, 0x13, 0x31, 0x7d, 0x33, 0x45, 0x3e, 0xb2, 0xe5, 0x4f, 0x48, 0x1f, 0x79,
	0x5f, 0x09, 0xab, 0xb1, 0x2b, 0xe5, 0x35, 0xbf, 0x6e, 0x12, 0xfe, 0xcf, 0x37, 0x7e, 0x60, 0xbe,
	0xe5, 0x3b, 0x60, 0xd4, 0xd1, 0x07, 0xda, 0x98, 0xf6, 0xb0, 0xad, 0xbe, 0xf6, 0x1b, 0x75, 0xab,
	0x9c, 0xf3, 0x4b, 0x1c, 0xc6, 0x31, 0xc1, 0xcd, 0x9f, 0x08, 0xd8, 0x07, 0xbf, 0xfa, 0xfc, 0x12,
	0xd8, 0x17, 0x85, 0xcd, 0x0d, 0x3f, 0xa9, 0x66, 0xcb, 0x7f, 0x7e, 0x5a, 0xdd, 0x89, 0xed, 0x02,
	0x92, 0x8f, 0x14, 0x39, 0x3f, 0x38, 0x3c, 0xcf, 0xaa, 0xb9, 0xfc, 0x49, 0x75, 0xea, 0x88, 0xfc,
	0x83, 0x26, 0xf2, 0xb0, 0xfc, 0x1a, 0x72, 0xb2, 0x40, 0x0f, 0x73, 0xc7, 0x8d, 0x14, 0x90, 0x07,
	0x23, 0x61, 0xfd, 0xc6, 0x34, 0x66, 0xdd, 0xae, 0x13, 0xfa, 0x99, 0xdf, 0xfe, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0xf0, 0x3f, 0x86, 0xbf, 0xe1, 0x03, 0x00, 0x00,
}
